### ISSUE TITLE
Not sure what this mod is, but it crashes my Minecraft

### ISSUE THREAD

**Issue by vinnyg0621** [tvanprooyen/mbm#2]
here's the report:

---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 11/16/20 1:31 PM
Description: Initializing game

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$0(BetterslabsClient.java:47)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient$$Lambda$3383/263625076.accept(Unknown Source)
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.<init>(ArtificeResourcePackImpl.java:80)
	at com.swordglowsblue.artifice.api.ArtificeResourcePack.ofAssets(ArtificeResourcePack.java:128)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:50)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:29)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:32)
	at net.minecraft.class_310.handler$zfg000$MinecraftClient(class_310.java:4866)
	at net.minecraft.class_310.<init>(class_310.java:592)
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
	at com.google.gson.JsonParser.parse(JsonParser.java:60)
	... 17 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.google.gson.JsonParser.parse(JsonParser.java:65)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$0(BetterslabsClient.java:47)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient$$Lambda$3383/263625076.accept(Unknown Source)
	at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.<init>(ArtificeResourcePackImpl.java:80)
	at com.swordglowsblue.artifice.api.ArtificeResourcePack.ofAssets(ArtificeResourcePack.java:128)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:50)
	at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:29)
	at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:32)
	at net.minecraft.class_310.handler$zfg000$MinecraftClient(class_310.java:4866)
	at net.minecraft.class_310.<init>(class_310.java:592)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
	at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1493959760 bytes (1424 MB) / 2147483648 bytes (2048 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Fabric Mods: 
		artifice: Artifice 0.13.2+1.16.3
		autoconfig1u: Auto Config v1 Updated 3.2.2
		betterslabs: Betterslabs 1.1.1
		blockus: Blockus 1.6.7+1.16.4
		bno: Basic Nether Ores 1.16.4-5.4.0-Fabric
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-config2: Cloth Config v4 4.8.2
		cloth-dynamic-registry-api-v1: Cloth Dynamic Registry API v1 1.4.9
		croptopia: Croptopia 1.0.5-1.16.3-FABRIC
		customstars: Custom Stars 0.4.1
		fabric: Fabric API 0.25.7+1.16
		fabric-api-base: Fabric API Base 0.2.0+9f0fb4b83a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.0.0+ec7e203b3a
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.4+c6a8ea893a
		fabric-command-api-v1: Fabric Command API (v1) 1.0.9+a4467d2a3a
		fabric-commands-v0: Fabric Commands (v0) 0.2.0+52d308363a
		fabric-containers-v0: Fabric Containers (v0) 0.1.8+045df74f3a
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.1.9+059ea8663a
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.2+b7f9825d3a
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.1+f8ac1db23a
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.0+16acbe5b3a
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.3+a4467d2a3a
		fabric-item-api-v1: Fabric Item API (v1) 1.2.0+f8ac1db23a
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.1+a4467d2a3a
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.1+730711c63a
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.0+3fa9f7c53a
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.0+74cc3b203a
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.1+432ea1883a
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.2+b764ce993a
		fabric-models-v0: Fabric Models (v0) 0.1.1+f8ac1db23a
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.5+b50ffc7b3a
		fabric-networking-v0: Fabric Networking (v0) 0.1.10+e00ecb5f3a
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.2+a89534ab3a
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.1+a4467d2a3a
		fabric-particles-v1: fabric-particles-v1 0.2.2+fb0d9b0e3a
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.6.1+a4467d2a3a
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.3.3+a4467d2a3a
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.3+a4467d2a3a
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.2.0+f8ac1db23a
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.4+f8ac1db23a
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.12+f8ac1db23a
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.1+f8ac1db23a
		fabric-rendering-v1: Fabric Rendering (v1) 1.3.1+f8ac1db23a
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.3.2+1944f3e03a
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.0+872498413a
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.0+f8ac1db23a
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.0.3+ac8e8c593a
		fabric-textures-v0: Fabric Textures (v0) 1.0.5+a4467d2a3a
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.5+c93221003a
		fabricloader: Fabric Loader 0.10.6+build.214
		midnight-hats: Midnight Hats 2.0.1
		minecraft: Minecraft 1.16.4
		mm: Manningham Mills 2.1
		modern_beta: Modern Beta Fabric 0.9.2
		modmenu: Mod Menu 1.14.9+build.13
		moreblocksmod: More Blocks Mod 1.0.0
		optifabric: OptiFabric 1.8.5
		rocks: This Rocks! 1.2.0
		statement: Statement 4.0.0+1.16.2
	Launched Version: fabric-loader-0.10.6+build.214-1.16.4
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: AMD Radeon(TM) Vega 3 Graphics GL version 4.6.13547 Compatibility Profile Context 25.20.15030.4, ATI Technologies Inc.
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	CPU: 4x AMD Ryzen 3 2200U with Radeon Vega Mobile Gfx 
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 9
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Builder's QOL Shaders V2.7.0.zip
	OpenGlVersion: 4.6.13547 Compatibility Profile Context 25.20.15030.4
	OpenGlRenderer: AMD Radeon(TM) Vega 3 Graphics
	OpenGlVendor: ATI Technologies Inc.
	CpuCount: 4

-- OptiFabric --
Details:
	OptiFine jar designed for: 1.16.4
	OptiFine jar version: OptiFine_1.16.4_HD_U_G5
	OptiFine jar status: Valid OptiFine installer
	OptiFine remapped jar: C:\Users\vinny.DESKTOP-HD3PDS0\OneDrive\Desktop\Minecraft\Modern beta 1.16\.optifine\OptiFine_1.16.4_HD_U_G5\Optifine-mapped.jar
	OptiFabric error: <None>

what mod is this?

**Comment by tvanprooyen** [comment]
Looking at this issue. It looks like the problem is with this mod Betterslabs (Bolded Below). They are creating JSON files on client side. Its nice code, but not the way Mojang has made it. I looked into the there source code and I'll post it down below where the issue is at. Unfortunately the issue isn't strictly MoreBlocksMod as it doesn't have it located in crash report. Other than at the bottom saying that it is a loaded mod. This would be an issue with how Betterslabs mod is attempting to interface with other mods textures and creating a slab from it. The thing I can do from my side is to make sure there is no Minecraft textures in MoreBlocksMod textures file (as this could try to create duplicates of one block). What Betterslabs mod should do is the try function as they create JSON files, so it doesn't crash the game.

com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.google.gson.JsonParser.parse(JsonParser.java:65)

**at dev.bodner.jack.betterslabs.client.BetterslabsClient.lambda$createPack$0(BetterslabsClient.java:47)**

at dev.bodner.jack.betterslabs.client.BetterslabsClient$$Lambda$3383/263625076.accept(Unknown Source)
at com.swordglowsblue.artifice.impl.ArtificeResourcePackImpl.(ArtificeResourcePackImpl.java:80)
at com.swordglowsblue.artifice.api.ArtificeResourcePack.ofAssets(ArtificeResourcePack.java:128)
at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:50)
at com.swordglowsblue.artifice.api.Artifice.registerAssets(Artifice.java:29)
at dev.bodner.jack.betterslabs.client.BetterslabsClient.createPack(BetterslabsClient.java:32)
at net.minecraft.class_310.handler$zfg000$MinecraftClient(class_310.java:4866)
at net.minecraft.class_310.(class_310.java:592)
at net.minecraft.client.main.Main.main(Main.java:177)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:224)
at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:141)
at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:27)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 5 path $
at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1559)
at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1401)
at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:542)
at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
at com.google.gson.JsonParser.parse(JsonParser.java:60)
... 17 more


Here is the issue from Betterslabs Mod that is the issue
47)  JsonObject blockstateObject = (JsonObject)jsonParser.parse(new InputStreamReader(stream));

Full java code in link
[](https://github.com/Eilux/BetterSlabs/blob/master/src/main/java/dev/bodner/jack/betterslabs/client/BetterslabsClient.java)

**Comment by tvanprooyen** [comment]
I double checked to see any Minecraft textures are in MoreBlocksMod textures and there isn't any.  It looks like this is already a current issue in BetterSlabs mod.

https://github.com/Eilux/BetterSlabs/issues/7
